//
// SetPasswordBindingModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class SetPasswordBindingModel: Codable {

    public var newPassword: String
    public var confirmPassword: String?
    public var passwordReminderPhrase: String?


    
    public init(newPassword: String, confirmPassword: String?, passwordReminderPhrase: String?) {
        self.newPassword = newPassword
        self.confirmPassword = confirmPassword
        self.passwordReminderPhrase = passwordReminderPhrase
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(newPassword, forKey: "NewPassword")
        try container.encodeIfPresent(confirmPassword, forKey: "ConfirmPassword")
        try container.encodeIfPresent(passwordReminderPhrase, forKey: "PasswordReminderPhrase")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        newPassword = try container.decode(String.self, forKey: "NewPassword")
        confirmPassword = try container.decodeIfPresent(String.self, forKey: "ConfirmPassword")
        passwordReminderPhrase = try container.decodeIfPresent(String.self, forKey: "PasswordReminderPhrase")
    }
}

