//
// UserLoginInfoViewModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class UserLoginInfoViewModel: Codable {

    public var loginProvider: String?
    public var providerKey: String?


    
    public init(loginProvider: String?, providerKey: String?) {
        self.loginProvider = loginProvider
        self.providerKey = providerKey
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(loginProvider, forKey: "LoginProvider")
        try container.encodeIfPresent(providerKey, forKey: "ProviderKey")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        loginProvider = try container.decodeIfPresent(String.self, forKey: "LoginProvider")
        providerKey = try container.decodeIfPresent(String.self, forKey: "ProviderKey")
    }
}

