//
// Attachment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class Attachment: Codable {

    public enum Status: String, Codable { 
        case publish = "publish"
        case future = "future"
        case draft = "draft"
        case pending = "pending"
        case _private = "private"
    }
    public enum CommentStatus: String, Codable { 
        case open = "open"
        case closed = "closed"
    }
    public enum PingStatus: String, Codable { 
        case open = "open"
        case closed = "closed"
    }
    public enum Template: String, Codable { 
        case empty = ""
    }
    public enum MediaType: String, Codable { 
        case image = "image"
        case file = "file"
    }
    /** The date the object was published, in the site&#39;s timezone. */
    public var date: Date?
    /** The date the object was published, as GMT. */
    public var dateGmt: Date?
    public var guid: PostGuid?
    /** Unique identifier for the object. */
    public var id: Int?
    /** URL to the object. */
    public var link: String?
    /** The date the object was last modified, in the site&#39;s timezone. */
    public var modified: Date?
    /** The date the object was last modified, as GMT. */
    public var modifiedGmt: Date?
    /** An alphanumeric identifier for the object unique to its type. */
    public var slug: String?
    /** A named status for the object. */
    public var status: Status?
    /** Type of Post for the object. */
    public var type: String?
    public var title: PostTitle?
    /** The ID for the author of the object. */
    public var author: Int?
    /** Whether or not comments are open on the object. */
    public var commentStatus: CommentStatus?
    /** Whether or not the object can be pinged. */
    public var pingStatus: PingStatus?
    /** Meta fields. */
    public var meta: Any?
    /** The theme file to use to display the object. */
    public var template: Template?
    /** Alternative text to display when attachment is not displayed. */
    public var altText: String?
    public var caption: AttachmentCaption?
    public var description: AttachmentDescription?
    /** Attachment type. */
    public var mediaType: MediaType?
    /** The attachment MIME type. */
    public var mimeType: String?
    /** Details about the media file, specific to its type. */
    public var mediaDetails: Any?
    /** The ID for the associated post of the attachment. */
    public var post: Int?
    /** URL to the original attachment file. */
    public var sourceUrl: String?


    
    public init(date: Date?, dateGmt: Date?, guid: PostGuid?, id: Int?, link: String?, modified: Date?, modifiedGmt: Date?, slug: String?, status: Status?, type: String?, title: PostTitle?, author: Int?, commentStatus: CommentStatus?, pingStatus: PingStatus?, meta: Any?, template: Template?, altText: String?, caption: AttachmentCaption?, description: AttachmentDescription?, mediaType: MediaType?, mimeType: String?, mediaDetails: Any?, post: Int?, sourceUrl: String?) {
        self.date = date
        self.dateGmt = dateGmt
        self.guid = guid
        self.id = id
        self.link = link
        self.modified = modified
        self.modifiedGmt = modifiedGmt
        self.slug = slug
        self.status = status
        self.type = type
        self.title = title
        self.author = author
        self.commentStatus = commentStatus
        self.pingStatus = pingStatus
        self.meta = meta
        self.template = template
        self.altText = altText
        self.caption = caption
        self.description = description
        self.mediaType = mediaType
        self.mimeType = mimeType
        self.mediaDetails = mediaDetails
        self.post = post
        self.sourceUrl = sourceUrl
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(date, forKey: "date")
        try container.encodeIfPresent(dateGmt, forKey: "date_gmt")
        try container.encodeIfPresent(guid, forKey: "guid")
        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(link, forKey: "link")
        try container.encodeIfPresent(modified, forKey: "modified")
        try container.encodeIfPresent(modifiedGmt, forKey: "modified_gmt")
        try container.encodeIfPresent(slug, forKey: "slug")
        try container.encodeIfPresent(status, forKey: "status")
        try container.encodeIfPresent(type, forKey: "type")
        try container.encodeIfPresent(title, forKey: "title")
        try container.encodeIfPresent(author, forKey: "author")
        try container.encodeIfPresent(commentStatus, forKey: "comment_status")
        try container.encodeIfPresent(pingStatus, forKey: "ping_status")
        try container.encodeIfPresent(meta, forKey: "meta")
        try container.encodeIfPresent(template, forKey: "template")
        try container.encodeIfPresent(altText, forKey: "alt_text")
        try container.encodeIfPresent(caption, forKey: "caption")
        try container.encodeIfPresent(description, forKey: "description")
        try container.encodeIfPresent(mediaType, forKey: "media_type")
        try container.encodeIfPresent(mimeType, forKey: "mime_type")
        try container.encodeIfPresent(mediaDetails, forKey: "media_details")
        try container.encodeIfPresent(post, forKey: "post")
        try container.encodeIfPresent(sourceUrl, forKey: "source_url")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        date = try container.decodeIfPresent(Date.self, forKey: "date")
        dateGmt = try container.decodeIfPresent(Date.self, forKey: "date_gmt")
        guid = try container.decodeIfPresent(PostGuid.self, forKey: "guid")
        id = try container.decodeIfPresent(Int.self, forKey: "id")
        link = try container.decodeIfPresent(String.self, forKey: "link")
        modified = try container.decodeIfPresent(Date.self, forKey: "modified")
        modifiedGmt = try container.decodeIfPresent(Date.self, forKey: "modified_gmt")
        slug = try container.decodeIfPresent(String.self, forKey: "slug")
        status = try container.decodeIfPresent(Status.self, forKey: "status")
        type = try container.decodeIfPresent(String.self, forKey: "type")
        title = try container.decodeIfPresent(PostTitle.self, forKey: "title")
        author = try container.decodeIfPresent(Int.self, forKey: "author")
        commentStatus = try container.decodeIfPresent(CommentStatus.self, forKey: "comment_status")
        pingStatus = try container.decodeIfPresent(PingStatus.self, forKey: "ping_status")
        meta = try container.decodeIfPresent(Any.self, forKey: "meta")
        template = try container.decodeIfPresent(Template.self, forKey: "template")
        altText = try container.decodeIfPresent(String.self, forKey: "alt_text")
        caption = try container.decodeIfPresent(AttachmentCaption.self, forKey: "caption")
        description = try container.decodeIfPresent(AttachmentDescription.self, forKey: "description")
        mediaType = try container.decodeIfPresent(MediaType.self, forKey: "media_type")
        mimeType = try container.decodeIfPresent(String.self, forKey: "mime_type")
        mediaDetails = try container.decodeIfPresent(Any.self, forKey: "media_details")
        post = try container.decodeIfPresent(Int.self, forKey: "post")
        sourceUrl = try container.decodeIfPresent(String.self, forKey: "source_url")
    }
}

