//
// CommentAuthorAvatarUrls.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Avatar URLs for the object author. */

open class CommentAuthorAvatarUrls: Codable {

    /** Avatar URL with image size of 24 pixels. */
    public var _24: String?
    /** Avatar URL with image size of 48 pixels. */
    public var _48: String?
    /** Avatar URL with image size of 96 pixels. */
    public var _96: String?


    
    public init(_24: String?, _48: String?, _96: String?) {
        self._24 = _24
        self._48 = _48
        self._96 = _96
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(_24, forKey: "24")
        try container.encodeIfPresent(_48, forKey: "48")
        try container.encodeIfPresent(_96, forKey: "96")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        _24 = try container.decodeIfPresent(String.self, forKey: "24")
        _48 = try container.decodeIfPresent(String.self, forKey: "48")
        _96 = try container.decodeIfPresent(String.self, forKey: "96")
    }
}

