//
// ModelError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class ModelError: Codable {

    public var code: String?
    public var message: String?
    public var data: ErrorData?


    
    public init(code: String?, message: String?, data: ErrorData?) {
        self.code = code
        self.message = message
        self.data = data
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(code, forKey: "code")
        try container.encodeIfPresent(message, forKey: "message")
        try container.encodeIfPresent(data, forKey: "data")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        code = try container.decodeIfPresent(String.self, forKey: "code")
        message = try container.decodeIfPresent(String.self, forKey: "message")
        data = try container.decodeIfPresent(ErrorData.self, forKey: "data")
    }
}

