//
// PostExcerpt.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The excerpt for the object. */

open class PostExcerpt: Codable {

    /** Excerpt for the object, as it exists in the database. */
    public var raw: String?
    /** HTML excerpt for the object, transformed for display. */
    public var rendered: String?
    /** Whether the excerpt is protected with a password. */
    public var protected: Bool?


    
    public init(raw: String?, rendered: String?, protected: Bool?) {
        self.raw = raw
        self.rendered = rendered
        self.protected = protected
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(raw, forKey: "raw")
        try container.encodeIfPresent(rendered, forKey: "rendered")
        try container.encodeIfPresent(protected, forKey: "protected")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        raw = try container.decodeIfPresent(String.self, forKey: "raw")
        rendered = try container.decodeIfPresent(String.self, forKey: "rendered")
        protected = try container.decodeIfPresent(Bool.self, forKey: "protected")
    }
}

