//
// AttachmentCaption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The attachment caption. */
open class AttachmentCaption: JSONEncodable {

    /** Caption for the attachment, as it exists in the database. */
    public var raw: String?
    /** HTML caption for the attachment, transformed for display. */
    public var rendered: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["raw"] = self.raw
        nillableDictionary["rendered"] = self.rendered

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

