//
// Attachment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Attachment: JSONEncodable {

    public enum Status: String { 
        case publish = "publish"
        case future = "future"
        case draft = "draft"
        case pending = "pending"
        case _private = "private"
    }
    public enum CommentStatus: String { 
        case open = "open"
        case closed = "closed"
    }
    public enum PingStatus: String { 
        case open = "open"
        case closed = "closed"
    }
    public enum Template: String { 
        case empty = ""
    }
    public enum MediaType: String { 
        case image = "image"
        case file = "file"
    }
    /** The date the object was published, in the site&#39;s timezone. */
    public var date: Date?
    /** The date the object was published, as GMT. */
    public var dateGmt: Date?
    public var guid: PostGuid?
    /** Unique identifier for the object. */
    public var id: Int32?
    /** URL to the object. */
    public var link: String?
    /** The date the object was last modified, in the site&#39;s timezone. */
    public var modified: Date?
    /** The date the object was last modified, as GMT. */
    public var modifiedGmt: Date?
    /** An alphanumeric identifier for the object unique to its type. */
    public var slug: String?
    /** A named status for the object. */
    public var status: Status?
    /** Type of Post for the object. */
    public var type: String?
    public var title: PostTitle?
    /** The ID for the author of the object. */
    public var author: Int32?
    /** Whether or not comments are open on the object. */
    public var commentStatus: CommentStatus?
    /** Whether or not the object can be pinged. */
    public var pingStatus: PingStatus?
    /** Meta fields. */
    public var meta: Any?
    /** The theme file to use to display the object. */
    public var template: Template?
    /** Alternative text to display when attachment is not displayed. */
    public var altText: String?
    public var caption: AttachmentCaption?
    public var description: AttachmentDescription?
    /** Attachment type. */
    public var mediaType: MediaType?
    /** The attachment MIME type. */
    public var mimeType: String?
    /** Details about the media file, specific to its type. */
    public var mediaDetails: Any?
    /** The ID for the associated post of the attachment. */
    public var post: Int32?
    /** URL to the original attachment file. */
    public var sourceUrl: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["date"] = self.date?.encodeToJSON()
        nillableDictionary["date_gmt"] = self.dateGmt?.encodeToJSON()
        nillableDictionary["guid"] = self.guid?.encodeToJSON()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["link"] = self.link
        nillableDictionary["modified"] = self.modified?.encodeToJSON()
        nillableDictionary["modified_gmt"] = self.modifiedGmt?.encodeToJSON()
        nillableDictionary["slug"] = self.slug
        nillableDictionary["status"] = self.status?.rawValue
        nillableDictionary["type"] = self.type
        nillableDictionary["title"] = self.title?.encodeToJSON()
        nillableDictionary["author"] = self.author?.encodeToJSON()
        nillableDictionary["comment_status"] = self.commentStatus?.rawValue
        nillableDictionary["ping_status"] = self.pingStatus?.rawValue
        nillableDictionary["meta"] = self.meta
        nillableDictionary["template"] = self.template?.rawValue
        nillableDictionary["alt_text"] = self.altText
        nillableDictionary["caption"] = self.caption?.encodeToJSON()
        nillableDictionary["description"] = self.description?.encodeToJSON()
        nillableDictionary["media_type"] = self.mediaType?.rawValue
        nillableDictionary["mime_type"] = self.mimeType
        nillableDictionary["media_details"] = self.mediaDetails
        nillableDictionary["post"] = self.post?.encodeToJSON()
        nillableDictionary["source_url"] = self.sourceUrl

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

