//
// CommentAuthorAvatarUrls.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Avatar URLs for the object author. */
open class CommentAuthorAvatarUrls: JSONEncodable {

    /** Avatar URL with image size of 24 pixels. */
    public var _24: String?
    /** Avatar URL with image size of 48 pixels. */
    public var _48: String?
    /** Avatar URL with image size of 96 pixels. */
    public var _96: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["24"] = self._24
        nillableDictionary["48"] = self._48
        nillableDictionary["96"] = self._96

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

