//
// ModelType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ModelType: JSONEncodable {

    /** All capabilities used by the post type. */
    public var capabilities: Any?
    /** A human-readable description of the post type. */
    public var description: String?
    /** Whether or not the post type should have children. */
    public var hierarchical: Bool?
    /** Human-readable labels for the post type for various contexts. */
    public var labels: Any?
    /** The title for the post type. */
    public var name: String?
    /** An alphanumeric identifier for the post type. */
    public var slug: String?
    /** Taxonomies associated with post type. */
    public var taxonomies: [String]?
    /** REST base route for the post type. */
    public var restBase: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["capabilities"] = self.capabilities
        nillableDictionary["description"] = self.description
        nillableDictionary["hierarchical"] = self.hierarchical
        nillableDictionary["labels"] = self.labels
        nillableDictionary["name"] = self.name
        nillableDictionary["slug"] = self.slug
        nillableDictionary["taxonomies"] = self.taxonomies?.encodeToJSON()
        nillableDictionary["rest_base"] = self.restBase

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

