//
// PostExcerpt.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The excerpt for the object. */
open class PostExcerpt: JSONEncodable {

    /** Excerpt for the object, as it exists in the database. */
    public var raw: String?
    /** HTML excerpt for the object, transformed for display. */
    public var rendered: String?
    /** Whether the excerpt is protected with a password. */
    public var protected: Bool?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["raw"] = self.raw
        nillableDictionary["rendered"] = self.rendered
        nillableDictionary["protected"] = self.protected

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

