//
// Status.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Status: JSONEncodable {

    /** The title for the status. */
    public var name: String?
    /** Whether posts with this status should be private. */
    public var _private: Bool?
    /** Whether posts with this status should be protected. */
    public var protected: Bool?
    /** Whether posts of this status should be shown in the front end of the site. */
    public var _public: Bool?
    /** Whether posts with this status should be publicly-queryable. */
    public var queryable: Bool?
    /** Whether to include posts in the edit listing for their post type. */
    public var showInList: Bool?
    /** An alphanumeric identifier for the status. */
    public var slug: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["private"] = self._private
        nillableDictionary["protected"] = self.protected
        nillableDictionary["public"] = self._public
        nillableDictionary["queryable"] = self.queryable
        nillableDictionary["show_in_list"] = self.showInList
        nillableDictionary["slug"] = self.slug

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

