//
// Tag.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Tag: JSONEncodable {

    public enum Taxonomy: String { 
        case category = "category"
        case postTag = "post_tag"
        case navMenu = "nav_menu"
        case linkCategory = "link_category"
        case postFormat = "post_format"
    }
    /** Unique identifier for the term. */
    public var id: Int32?
    /** Number of published posts for the term. */
    public var count: Int32?
    /** HTML description of the term. */
    public var description: String?
    /** URL of the term. */
    public var link: String?
    /** HTML title for the term. */
    public var name: String?
    /** An alphanumeric identifier for the term unique to its type. */
    public var slug: String?
    /** Type attribution for the term. */
    public var taxonomy: Taxonomy?
    /** Meta fields. */
    public var meta: Any?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["count"] = self.count?.encodeToJSON()
        nillableDictionary["description"] = self.description
        nillableDictionary["link"] = self.link
        nillableDictionary["name"] = self.name
        nillableDictionary["slug"] = self.slug
        nillableDictionary["taxonomy"] = self.taxonomy?.rawValue
        nillableDictionary["meta"] = self.meta

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

